### PR TITLE
Add Gitter badge to README

### PR DESCRIPTION
**Pull request by bittner**
This adds another sweet badge to the top of the README. This time leading to our magnificent Gitter chat lobby. Welcome to the wonderful world of Python! :100:  :tada:

### CODE REVIEW

**Comment by bittner** [comment]
I wonder whether "continuous-integration/appveyor/branch" will ever turn green. Looks like the integration with AppVeyor is broken or something. :confused:

**Comment by bittner** [comment]
The AppVeyor [project settings](https://ci.appveyor.com/project/cool-RR/pythonturtle/settings) do have a 'Do not build on "Pull request" events' option, but it's turned off. Not sure what's happening.

**Comment by bittner** [comment]
With the 'Do not build on "Pull request" events' option on it's even worse: No build is triggered at all.

I'll try with the 'Do not build on "Push" events' option activated.

**Comment by bittner** [comment]
It looks like there is something wrong with the integration of AppVeyor here on GitHub. The AppVeyor plugin (or what it is) wants to act on a "build for branch completed" event, but this is not arriving. There's not even a "Details" link, probably because there's no build at all.

@cool-RR could you check in the [Webhooks settings](https://github.com/cool-RR/PythonTurtle/settings/hooks) and the [Integration settings](https://github.com/cool-RR/PythonTurtle/settings/installations) here on GitHub whether everything looks plausible?

**Comment by bittner** [comment]
@cool-RR There's also an [Update installations](https://ci.appveyor.com/account/cool-RR/authorizations) button in the "Authorizations" section of the AppVeyor "Account settings". You may want to try triggering this if everything else fails. (Maybe a webhook was not correctly installed/configured.)

**Comment by cool-RR** [comment]
> @cool-RR could you check in the [Webhooks settings](https://github.com/cool-RR/PythonTurtle/settings/hooks) and the [Integration settings](https://github.com/cool-RR/PythonTurtle/settings/installations) here on GitHub whether everything looks plausible?

Sent you screenshots by email, let me know if something is wrong.

**Comment by cool-RR** [comment]
Update installations doesn't seem to do anything since it leads me to a GitHub settings page with the save button disabled, because all the settings are perfect. It'll probably become enabled if I'll change the settings.

**Comment by bittner** [comment]
I've taken a look at your screenshots. I can't spot anything that might be wrong. There could be an issue with the AppVeyor Application, but it might just be an authorization problem ([as mentioned in this StackOverflow answer](https://stackoverflow.com/questions/32607885/appveyor-doesnt-update-github-pull-request-with-the-build-status)).

- Could you try to revoke authorization and add authorization anew afterwards?
- If that doesn't help could you open a ticket with AppVeyor? Maybe it's a bug.

**Comment by cool-RR** [comment]
> Could you try to revoke authorization and add authorization anew afterwards?

Did that now. Not sure how to check whether it works.

Regarding opening a bug, do you mind doing that? If they want my authorization they can email me and I'll confirm you can do anything on my behalf.

**Comment by cool-RR** [comment]
I don't understand. Is that a setting for protected branches called "pr only"? I looked there and couldn't find it. I sent you the screenshots of these pages, can you find it in there? Am I supposed to make a branch called "pr only"?

**Comment by bittner** [comment]
You're right. There is actually no such option (anymore), because AppVeyor is integrated via their GitHub App (and not via Webhooks).

**Comment by bittner** [comment]
No! Actually, it's the "Branch protection" page you have to look at! The mentioned option is _there_. (See [here](https://help.appveyor.com/discussions/problems/3612-github-showing-multiple-checks) for an example screenshot.) -- Can you check and make sure that only "continuous-integration/appveyor/pr" is checked?

**Comment by cool-RR** [comment]
Okay, done. I left pr and Shippable checked.

**Comment by bittner** [comment]
That seems to work fine now. (Phew! That was quite some work until here.) I just notice that now Travis CI is the only one not showing the "Required" label. Not sure why, do you? (Note: It's fine like this, but if we really want to make it perfect...)

**Comment by bittner** [comment]
As you saw, I've asked Shippable support to check what's now still wrong.

Re Travis and the "Required" tag: This is most probably the same as with AppVeyor before. It's in the "Protected Branches" screen where the option should be checked.

**Comment by cool-RR** [comment]
> Ram, can you edit the "Protected Branches" again and uncheck the "Required" for all integrations?

Done.

**Pull request merged**
