### PR TITLE
Migrate tests to pytest

### PR DESCRIPTION
**Pull request by bittner**
These "tests" totally don't make sense. They really do what PyLint is already doing checking imports (but, well, we don't even care if it fails -- it's a shame). But, heck, the test infrastructure is now in place!

### CODE REVIEW

**Comment by bittner** [comment]
Every statement that thoroughly executes importing `wx` fails. It's a pain. :unamused:

**Comment by bittner** [comment]
Tests with pytest now pass, yay! :tada:  (The build only fails for macOS; I'll tackle that separately.)

I had to install wxPython correctly, plus ensure a prerequisite (see https://github.com/wxWidgets/Phoenix/issues/1028 for explanations).

I'll remove the behave tests from the code base, then the PR is ready for merging. :+1:

**Comment by cool-RR** [comment]
So merge now, or wait?

**Comment by bittner** [comment]
Hang on a second.

If Python 3.7 now passes (too) then you can merge. Otherwise I remove the (then unnecessary) commit again.

**Comment by bittner** [comment]
[pytest complains](https://travis-ci.org/cool-RR/PythonTurtle/jobs/437273443#L844) about an `invalid escape sequence \.` in [shelltoprocess/forkedpyshell.py](https://github.com/cool-RR/PythonTurtle/blob/master/pythonturtle/shelltoprocess/forkedpyshell.py#L777), line 777.

Can you spot what's wrong? Does a period have to be specified differently here? (or with Python 3?)

**Comment by bittner** [comment]
I removed the installation of ` libgtk-3-dev` and `python3-opengl` on Travis again. It somewhat looks like the OpenGL library needed for Python 3.7 is not available on Xenial, only on Artful, Bionic, Cosmic (which makes sense: there was no Python 3.7 before 17.10, I believe).

Hence, we'll probably not be able to make Python 3.7 pass on Travis as long as they don't provide a newer build image (e.g. based on Bionic).

Fine like this. You can merge! :+1:

**Pull request merged**
