### PR TITLE
Port to wxPython 4.0 + Python 3.6, enhance About dialog

### PR DESCRIPTION
**Pull request by bittner**
These changes make PythonTurtle run with Python 3.6 and wxPython 4.0

I've also fixed the missing image in the About dialog and added additional details there.

Please, review with care: I've also slightly modified the copyright portion of the license, added the list of developers to the About dialog, and adjusted the version number.

Note that I've only manually verified on GNU/Linux (Ubuntu 18.04.1 LTS Bionic) that the application runs, with the system defaults of Python and wxPython as noted in the README.

Fixes issue #99.

(I've not tried PyInstaller with the code changes yet. This will come next. Step by step, one thing after the other.)

### CODE REVIEW

**Comment by cool-RR** [comment]
Great work, thank you! I went over the code and it looks good. Haven't tried running, I'm relying on your testing. 

Note: I prefer `import queue` and `except queue.Empty` rather than `from queue import Empty`. But that's not critical.

**Comment by bittner** [comment]
> I'm relying on your testing.

I'm not testing. Testing is running automated tests. We don't have tests. (I'm not trying to be funny.)

>  I prefer `import queue` and `except queue.Empty` rather than

I understand. It's more explicit this way, you're right.

By the way, the whole [dumpqueue](https://github.com/cool-RR/PythonTurtle/blob/master/src/misc/dumpqueue.py) module is somewhat too shallow. And it's only [imported in a single place](https://github.com/cool-RR/PythonTurtle/blob/master/src/turtlewidget.py#L5). With that little functionality a dedicated module almost makes no sense.

**Comment by bittner** [comment]
Thanks for merging! :+1: 

(Sorry, for not saying this earlier.)

**Comment by cool-RR** [comment]
Re: testing, I think that manual testing still falls under "testing". As
long as you ran it and gave the turtle a few commands and looked at the
help screen, that's good enough for now.

**Pull request merged**
