### PR TITLE
Add test+build infrastructure (Tox and Travis CI)

### PR DESCRIPTION
**Pull request by bittner**
First steps towards automatic builds. Adds:

- a Tox configuration for running linting and tests (locally), and
- a Travis CI configuration.

See https://travis-ci.org/bittner/PythonTurtle while I'm testing the results of this implementation.

### CODE REVIEW

**Comment by cool-RR** [comment]
Great job!

**Comment by bittner** [comment]
You now need to activate this repository on Travis CI:

1. Log in to your Travis CI account
1. Go to https://travis-ci.org/cool-RR/PythonTurtle
1. Push the "Activate this repository" button

**Comment by cool-RR** [comment]
It wasn't exactly a button like you described, but I think I activated it,
could you verify?

**Comment by bittner** [comment]
Yeah, that looks good! https://travis-ci.org/cool-RR/PythonTurtle

Next Steps
------------

1. I'll add a cute **build status button** on top  of the README for this.
1. I'll make sure we get **a green tick** for the build status for new commits and PRs.

Afterwards, I'll try to:

1. Make the code base comply with PEP8 using `flake8` linting.
1. Fix issues Pylint complains about.

Finally,  the less trivial tasks:

1. Figure out whether I can port the codebase to wxgtk4.0, still staying compatible withwxgtk3.0. (This may be impractical, we'll see.) -- #99 
1. Make the code base work across all Python version we're testing against (including Python 3 and PyPy).
1. Add a few tests that actually makes sense and help with refactoring.

**Comment by cool-RR** [comment]
Sounds good to me!

**Comment by bittner** [comment]
Thanks for merging so quickly, by the way! :+1: :smiley:

**Pull request merged**
