### PR TITLE
Build Linux + macOS bundles (Travis), build EXE (AppVeyor)

### PR DESCRIPTION
**Pull request by bittner**
- Use absolute import in `__main__.py` for PyInstaller to work
- Add AppVeyor CI configuration

### CODE REVIEW

**Comment by bittner** [comment]
Can you create an account at [AppVeyor](https://www.appveyor.com/) and enable automatic builds for this repository, please?

This way we should see what AppVeyor is doing on Windows, with the configuration in this PR.

**Comment by bittner** [comment]
Can you create an account at [AppVeyor](https://www.appveyor.com/) and enable automatic builds for this repository, please?

This way we should see what AppVeyor is doing on Windows, with the configuration in this PR.

**Comment by cool-RR** [comment]
I created an AppVeyor project for this repo but I'm not sure how to enable
automatic builds. Also I tried to add you as a collaborator but I couldn't
figure out how to do that. I went through the settings pages but no luck.
Any clues?

**Comment by bittner** [comment]
AppVeyor has a horr`^H^H^H^H^H` user interface that is not meant to be loved. I have suffered this morning, too.  :unamused:

I think the users depend on what you have configured on GitHub (you grant the CI access to your GitHub organizations, and they allow access to accounts listed there; that's how CI services usually do it).

I'll try top push a change, then we maybe see something moving. Or can you trigger a build manually in your account?

**Comment by bittner** [comment]
It doesn't look like a build on AppVeyor was triggered. Can you check in the project settings of this repository on GitHub whether you have granted access to AppVeyor?

**Comment by cool-RR** [comment]
"Can you check in the project settings of this repository on GitHub whether you have granted access to AppVeyor?" I confirmed it's granted. (It was that way from before I made the check.)

"can you trigger a build manually in your account?" Did that now.

**Comment by bittner** [comment]
Can you share the link to the AppVeyor project? Please, also try whether the URL is accessible when you're not logged in into your AppVeyor account (i.e. anonymous access is allowed).

**Comment by bittner** [comment]
AppVeyor builds are not triggered. There should be another link next to Travis CI here in the UI. Can you check what's wrong? Maybe AppVeyor has support tickets, or infos that help pinning the problem in their knowledge base.

**Comment by bittner** [comment]
Can you please also create an OAuth Token on GitHub via `travis setup releases`? (see Travis [docs](https://docs.travis-ci.com/user/deployment/releases/#authenticating-with-an-oauth-token))

I let Travis build [a Linux bundle](https://travis-ci.org/cool-RR/PythonTurtle/builds/436630953) and upload it to GitHub. That's where we need the encrypted OAuth Token. I have the code already prepared, only the token is now missing.

**Comment by bittner** [comment]
If AppVeyor proves to be too cumbersome we can try [Shippable](http://docs.shippable.com/platform/tutorial/workflow/jobs-windows/). They provide Windows builds since recently. Do you want to try to create an account?

**Comment by cool-RR** [comment]
I created an account, and enabled this project: https://app.shippable.com/github/cool-RR/PythonTurtle/dashboard

I'll do the oauth token later.

**Comment by cool-RR** [comment]
Could you tell me which commands to run for the oauth token?

**Comment by bittner** [comment]
The `travis` command and a link to the related docs are in [the comment above](https://github.com/cool-RR/PythonTurtle/pull/123#issuecomment-426653164). :smiley:

**Comment by bittner** [comment]
The builds on AppVeyor seem to work now! Awesome! :tada: 

Can you try [downloading](https://ci.appveyor.com/project/cool-RR/pythonturtle/build/1.0.7/artifacts) and running the .EXE file that was built? The build spits out warnings all the way down, but who knows? Maybe it's working anyway.

> I created an account, and enabled this project: https://app.shippable.com/github/cool-RR/PythonTurtle/dashboard

Cool! You need to make sure you have Windows builds enabled (as of the link in [the comment above](https://github.com/cool-RR/PythonTurtle/pull/123#issuecomment-426670818)). I've been told by their support that, currently, we can only run Linux builds _or_ Windows builds (for free) from the same account or GitHub organization.

**Comment by bittner** [comment]
I think, we could merge this PR now. I've packed more into it than originally planned.

This would also trigger an upload to PyPI (and we could see if it works or why it fails).

**Comment by cool-RR** [comment]
Great job! I downloaded the exe and it worked! It crashed after exiting the program, but that's probably because of a bug we have. 

Do you still have interest in Shippable?

**Comment by bittner** [comment]
> Do you still have interest in Shippable?

Yes, I'd like to get it running. Just to verify that there's a working alternative to AppVeyor. This will also give us a feeling which of the two is easier to handle, has a nicer UI, etc.

What's still missing now with both Travis and AppVeyor (and Shippable of course) is the automatic upload of created application bundles (executables) to GitHub when a tag is pushed. We need to work on that. :point_up: 

P.S.: Have you bought your space suit, now that we're getting ready to fly to mars? :smile:

**Comment by bittner** [comment]
Re Shippable: Can you verify you have done all steps from **Section 1** in Shippable's [instructions for Windows builds](http://docs.shippable.com/platform/tutorial/workflow/jobs-windows/)?

**Comment by cool-RR** [comment]
I added you as an administrator on AppVeyor, let me know whether that worked.

**Comment by cool-RR** [comment]
I've added you as a collaborator on GitHub, I believe that'll make you a collaborator on Shippable, let me know if it doesn't. 

I haven't done anything from the Shippable instructions. Looking at it now it says I need to "Purchase the on-demand WindowsServer 2016 SKU". So, that costs money?

**Comment by bittner** [comment]
Hi Ram,

No, it shouldn't cost money. Shippable support told me that we need to
remove the Linux capabilities (repos that trigger Linux builds, probably)
from the account. Because we can only have either Linux or Windows builds
enabled, currently. In any case, if it shows something to pay, this should
go away once you remove the other option (repo, or whatever it is).

I'll forward you all the communication I have received by email. The chat
history on the website may not be included, but I'm not sure.

Kind regards,
Peter

Am Do., 4. Okt. 2018 um 23:06 Uhr schrieb Ram Rachum <
notifications@github.com>:

**Comment by cool-RR** [comment]
Weren't you made an administrator on the Shippable project? https://app.shippable.com/github/cool-RR/PythonTurtle/settings I hope I can make you an administrator so you could do it. 

If not let me know and I'll contact their support.

**Pull request merged**
