### PR TITLE
Add encrypted PyPI password

### PR DESCRIPTION
**Pull request by bittner**
As of https://github.com/cool-RR/PythonTurtle/pull/117#issuecomment-425729848.

### CODE REVIEW

**Comment by bittner** [comment]
Please wait, until the build is green. Even for seemingly "stupid" changes. :+1:

**Comment by cool-RR** [comment]
Sure. Do you know if there's a way to tell GitHub "merge this when it's
green"? Instead of checking back like an automaton.

**Comment by bittner** [comment]
Seems to fail for an [authentication error](https://travis-ci.org/cool-RR/PythonTurtle/jobs/435282960#L691). :confused: 

Was it the PyPI password of your `coolRR` user that you encrypted?

**Comment by bittner** [comment]
... and the publish step was executed even w/o pushing a Git tag? [It shouldn't!](https://github.com/cool-RR/PythonTurtle/blob/master/.travis.yml#L33-L34) -- Ah, Travis, you're a pain.

**Comment by cool-RR** [comment]
> Was it the PyPI password of your `coolRR` user that you encrypted?

Yep.

**Comment by cool-RR** [comment]
I got a bit lost in the conversation here, if you need me to do something let me know.

**Comment by bittner** [comment]
Could you try to push a tag to this repository now? e.g.
```bash
$ git checkout master
$ git tag 0.3.0
$ git push --tags
```
I want to see the automatic publishing on PyPI working. Cross your fingers! :crossed_fingers:

**Comment by cool-RR** [comment]
Pushed the tag.

**Comment by bittner** [comment]
[Travis says](https://travis-ci.org/cool-RR/PythonTurtle/jobs/435947427#L538), you didn't do this from the `master` branch:

> Skipping a deployment with the pypi provider because this branch is not permitted: 0.3.0

Can you try again? Ideally, delete the tag you added beforehand.

**Comment by cool-RR** [comment]
Pushed tag 0.3.1 now.

**Pull request merged**
